name: Despliegue de AWS CDK y Next.js

on:
  push:
    branches:
      - main

jobs:
  deploy_cdk:
    runs-on: ubuntu-latest
    defaults:
      run:
      # Mobile folder working directory.
        working-directory: aws
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            aws:
              - '../../aws/**'
      - name: Instalar dependencias de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install AWS CDK
        run: 'npm ci'
      # - name: Instalar AWS CLI
      #   run: |
      #     curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install
      #     aws --version
      - name: Desplegar AWS CDK
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: npx cdk deploy --app 'node bin/stack.js' --require-approval never